CREATE TABLE [dbo].[Customer] (
    [Id]                       UNIQUEIDENTIFIER   NOT NULL,
    [Name]                     NVARCHAR (250)     NULL,
    [FirstName]                NVARCHAR (250)     NULL,
    [LastName]                 NVARCHAR (250)     NULL,
    [SocialSecurityNumber]     NVARCHAR (50)      NULL,
    [MobileNumber]             NVARCHAR (50)      NULL,
    [AddressLineOne]           NVARCHAR (250)     NULL,
    [AddressLineTwo]           NVARCHAR (250)     NULL,
    [City]                     NVARCHAR (250)     NULL,
    [Postcode]                 NVARCHAR (250)     NULL,
    [TelephoneNumber]          NVARCHAR (250)     NULL,
    [Email]                    NVARCHAR (250)     NULL,
    [Scope]                    NVARCHAR (150)     NULL,
    [DateOfBirth]              DATETIMEOFFSET (7) NULL,
    [CustomerReference]        NVARCHAR (60)      NULL,
    [BusinessType]             NVARCHAR (10)      NULL,
    [CompanyType]              NVARCHAR (250)     NULL,
    [ParentOrganisationNumber] NVARCHAR (250)     NULL,
    [ParentOrganisationName]   NVARCHAR (250)     NULL,
    [VisitingAddressLineOne]   NVARCHAR (250)     NULL,
    [VisitingAddressLineTwo]   NVARCHAR (250)     NULL,
    [VisitingAddressCity]      NVARCHAR (250)     NULL,
    [VisitingAddressPostcode]  NVARCHAR (250)     NULL,
    [VisitingAddressCountry]   NVARCHAR (250)     NULL,
    [Fax]                      NVARCHAR (60)      NULL,
    [Website]                  NVARCHAR (250)     NULL,
    [UWInformation]            NVARCHAR (250)     NULL,
    [InvoiceEmail]             NVARCHAR (250)     NULL,
    [Country]                  NVARCHAR (250)     NULL,
    [CompanyTypeLocalised]     NVARCHAR (250)     NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

