CREATE TABLE [dbo].[Policy] (
    [Id]                        UNIQUEIDENTIFIER   NOT NULL,
    [PolicyId]                  UNIQUEIDENTIFIER   NOT NULL,
    [PolicyVersion]             INT                NOT NULL,
    [ContractRef]               NVARCHAR (250)     NULL,
    [CustomerId]                UNIQUEIDENTIFIER   NULL,
    [TransactionDate]           DATETIMEOFFSET (7) NULL,
    [ChangeCause]               NVARCHAR (250)     NULL,
    [PolicyStartDate]           DATETIMEOFFSET (7) NULL,
    [PolicyEndDate]             DATETIMEOFFSET (7) NULL,
    [PartnerId]                 UNIQUEIDENTIFIER   NULL,
    [ProductName]               NVARCHAR (250)     NULL,
    [ProductId]                 UNIQUEIDENTIFIER   NULL,
    [FinalAnnualPremiumIncTax]  DECIMAL (18, 5)    NULL,
    [FinalAnnualTax]            DECIMAL (18, 5)    NULL,
    [NumInsuredObjects]         INT                NULL,
    [ChangeQuoteDate]           DATETIMEOFFSET (7) NULL,
    [ChangeQuoteUser]           NVARCHAR (250)     NULL,
    [ChangeQuoteUserId]         UNIQUEIDENTIFIER   NULL,
    [ChangePurchaseUser]        NVARCHAR (250)     NULL,
    [ChangePurchaseUserId]      UNIQUEIDENTIFIER   NULL,
    [Scope]                     NVARCHAR (150)     NULL,
    [BrokerOrganisationId]      UNIQUEIDENTIFIER   NULL,
    [BrokerOfficeId]            UNIQUEIDENTIFIER   NULL,
    [BrokerPersonId]            UNIQUEIDENTIFIER   NULL,
    [CommissionForNewSales]     DECIMAL (18, 5)    NULL,
    [AggregateId]               UNIQUEIDENTIFIER   NULL,
    [PolicyType]                NVARCHAR (60)      NULL,
    [FrontingFeeAmount]         DECIMAL (18, 5)    NULL,
    [CreatedPurchaseUserId]     UNIQUEIDENTIFIER   NULL,
    [CreatedPurchaseUser]       NVARCHAR (250)     NULL,
    [Deductible]                DECIMAL (18, 5)    NULL,
    [DeductibleCurrency]        NVARCHAR (3)       NULL,
    [FrontingCompanyId]         UNIQUEIDENTIFIER   NULL,
    [FrontingCompany]           NVARCHAR (250)     NULL,
    [ChangeSourceRef]           NVARCHAR (250)     NULL,
    [TotalPeriodPremiumIncTax]  DECIMAL (18, 5)    NULL,
    [TotalPeriodTax]            DECIMAL (18, 5)    NULL,
    [Currency]                  NVARCHAR (3)       NULL,
    [PaymentsAccountId]         UNIQUEIDENTIFIER   NULL,
    [ChangeSourceId]            UNIQUEIDENTIFIER   NULL,
    [UWYear]                    NVARCHAR (60)      NULL,
    [ProductDiscountPercentage] DECIMAL (18, 5)    NULL,
    [ProductDiscount]           DECIMAL (18, 5)    NULL,
    [CarrierId]                 NVARCHAR (250)     NULL,
    [SkipClaimHandling]         BIT                NULL,
    CONSTRAINT [PK_Policy] PRIMARY KEY CLUSTERED ([Id] ASC)
);

